CBMC version 5.0 64-bit macos
Parsing COV_harness.c
Parsing BRANCHCOV_mutant100065_qsort2.c
Converting
Type-checking BRANCHCOV_mutant100065_qsort2
file BRANCHCOV_mutant100065_qsort2.c line 14 function quickSort: function `printf' is not declared
file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort: function `partition' is not declared
Type-checking COV_harness
file COV_harness.c line 33 function main: function `assert' is not declared
warning: implicit function declaration "printf"
old definition in module BRANCHCOV_mutant100065_qsort2 file BRANCHCOV_mutant100065_qsort2.c line 14 function quickSort
signed int (void)
new definition in module COV_harness file /usr/include/stdio.h line 259
signed int (const char *, ...)
Generating GOTO Program
Adding CPROVER library
Function Pointer Removal
Partial Inlining
Generic Property Instrumentation
SWITCHING TO ASSUME: 0 + (long int)(signed long int)i * (long int)4 >= 0
SWITCHING TO ASSUME: (signed long int)i < 3l
SWITCHING TO ASSUME: 0 + (long int)(signed long int)i * (long int)4 >= 0
SWITCHING TO ASSUME: (signed long int)i < 3l
WAS ASSERT
SWITCHING TO ASSUME: !(a + (signed long int)l == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)l)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)l) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)l) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)l) || !(POINTER_OFFSET(a + (signed long int)l) < 0 || POINTER_OFFSET(a + (signed long int)l) + 4 > OBJECT_SIZE(a + (signed long int)l))
SWITCHING TO ASSUME: !(a + (signed long int)i == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)i)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)i) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)i) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)i) || !(POINTER_OFFSET(a + (signed long int)i) < 0 || POINTER_OFFSET(a + (signed long int)i) + 4 > OBJECT_SIZE(a + (signed long int)i))
SWITCHING TO ASSUME: !(a + (signed long int)j == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)j)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)j) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)j) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)j) || !(POINTER_OFFSET(a + (signed long int)j) < 0 || POINTER_OFFSET(a + (signed long int)j) + 4 > OBJECT_SIZE(a + (signed long int)j))
SWITCHING TO ASSUME: !(a + (signed long int)i == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)i)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)i) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)i) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)i) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)i) || !(POINTER_OFFSET(a + (signed long int)i) < 0 || POINTER_OFFSET(a + (signed long int)i) + 4 > OBJECT_SIZE(a + (signed long int)i))
SWITCHING TO ASSUME: !(a + (signed long int)j == ((signed int *)NULL))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)j) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)j) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)j) || !(POINTER_OFFSET(a + (signed long int)j) < 0 || POINTER_OFFSET(a + (signed long int)j) + 4 > OBJECT_SIZE(a + (signed long int)j))
SWITCHING TO ASSUME: !(a + (signed long int)l == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)l)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)l) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)l) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)l) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)l) || !(POINTER_OFFSET(a + (signed long int)l) < 0 || POINTER_OFFSET(a + (signed long int)l) + 4 > OBJECT_SIZE(a + (signed long int)l))
SWITCHING TO ASSUME: !(a + (signed long int)j == ((signed int *)NULL))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)j) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)j) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)j) || !(POINTER_OFFSET(a + (signed long int)j) < 0 || POINTER_OFFSET(a + (signed long int)j) + 4 > OBJECT_SIZE(a + (signed long int)j))
SWITCHING TO ASSUME: !(a + (signed long int)j == ((signed int *)NULL))
SWITCHING TO ASSUME: !INVALID-POINTER(a + (signed long int)j)
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_deallocated))
SWITCHING TO ASSUME: !(POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_dead_object))
SWITCHING TO ASSUME: POINTER_OBJECT(a + (signed long int)j) == POINTER_OBJECT(__CPROVER_malloc_object) ==> !(POINTER_OFFSET(a + (signed long int)j) < 0 || (unsigned long int)(POINTER_OFFSET(a + (signed long int)j) + 4) > __CPROVER_malloc_size)
SWITCHING TO ASSUME: DYNAMIC_OBJECT(a + (signed long int)j) || !(POINTER_OFFSET(a + (signed long int)j) < 0 || POINTER_OFFSET(a + (signed long int)j) + 4 > OBJECT_SIZE(a + (signed long int)j))
Starting Bounded Model Checking
Unwinding loop main.0 iteration 1 (4 max) file COV_harness.c line 17 function main thread 0
Unwinding loop main.0 iteration 2 (4 max) file COV_harness.c line 17 function main thread 0
Unwinding loop main.0 iteration 3 (4 max) file COV_harness.c line 17 function main thread 0
Not unwinding loop main.0 iteration 4 (4 max) file COV_harness.c line 17 function main thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 1 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 2 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 2 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 1 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 2 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 2 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 3 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding recursion quickSort iteration 4 (4 max)
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.2 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Unwinding loop partition.0 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.0 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Not unwinding loop partition.0 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 40 function partition thread 0
Unwinding loop partition.1 iteration 1 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 2 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Unwinding loop partition.1 iteration 3 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.1 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 44 function partition thread 0
Not unwinding loop partition.2 iteration 4 (4 max) file BRANCHCOV_mutant100065_qsort2.c line 35 function partition thread 0
Not unwinding recursion quickSort iteration 5 (4 max)
Unwinding loop main.1 iteration 1 (4 max) file COV_harness.c line 26 function main thread 0
Unwinding loop main.1 iteration 2 (4 max) file COV_harness.c line 26 function main thread 0
Unwinding loop main.1 iteration 3 (4 max) file COV_harness.c line 26 function main thread 0
Not unwinding loop main.1 iteration 4 (4 max) file COV_harness.c line 26 function main thread 0
size of program expression: 18554 steps
simple slicing removed 4 assignments
Generated 298 VCC(s), 298 remaining after simplification
Passing problem to propositional reduction
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.0 without simplifier
1589655 variables, 6077233 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Runtime decision procedure: 56.544s
Beautifying counterexample (guards)
weight 11
Solving with MiniSAT 2.2.0 without simplifier
1589655 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 7
Solving with MiniSAT 2.2.0 without simplifier
1589656 variables, 5089210 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1589657 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 5
Solving with MiniSAT 2.2.0 without simplifier
1589657 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 4
Solving with MiniSAT 2.2.0 without simplifier
1589658 variables, 5089210 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1589659 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 3
Solving with MiniSAT 2.2.0 without simplifier
1589660 variables, 5089210 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1589661 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 2
Solving with MiniSAT 2.2.0 without simplifier
1589662 variables, 5089210 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1589663 variables, 5089210 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 1
Solving with MiniSAT 2.2.0 without simplifier
1589664 variables, 5089210 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1589665 variables, 5089212 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
Solving with MiniSAT 2.2.0 without simplifier
1589665 variables, 5089212 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Beautifying counterexample (values)
weight 2147483648
Solving with MiniSAT 2.2.0 without simplifier
1591904 variables, 5037231 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591905 variables, 5037243 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591906 variables, 5033114 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 1073741824
Solving with MiniSAT 2.2.0 without simplifier
1591907 variables, 5010228 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591908 variables, 5010219 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 536870912
Solving with MiniSAT 2.2.0 without simplifier
1591909 variables, 4815579 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 268435456
Solving with MiniSAT 2.2.0 without simplifier
1591910 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 134217728
Solving with MiniSAT 2.2.0 without simplifier
1591911 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 67108864
Solving with MiniSAT 2.2.0 without simplifier
1591912 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 33554432
Solving with MiniSAT 2.2.0 without simplifier
1591913 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 16777216
Solving with MiniSAT 2.2.0 without simplifier
1591914 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 8388608
Solving with MiniSAT 2.2.0 without simplifier
1591915 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 4194304
Solving with MiniSAT 2.2.0 without simplifier
1591916 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 2097152
Solving with MiniSAT 2.2.0 without simplifier
1591917 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 1048576
Solving with MiniSAT 2.2.0 without simplifier
1591918 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 524288
Solving with MiniSAT 2.2.0 without simplifier
1591919 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 262144
Solving with MiniSAT 2.2.0 without simplifier
1591920 variables, 4815560 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 131072
Solving with MiniSAT 2.2.0 without simplifier
1591921 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 65536
Solving with MiniSAT 2.2.0 without simplifier
1591922 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 32768
Solving with MiniSAT 2.2.0 without simplifier
1591923 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 16384
Solving with MiniSAT 2.2.0 without simplifier
1591924 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 8192
Solving with MiniSAT 2.2.0 without simplifier
1591925 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 4096
Solving with MiniSAT 2.2.0 without simplifier
1591926 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 2048
Solving with MiniSAT 2.2.0 without simplifier
1591927 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 1024
Solving with MiniSAT 2.2.0 without simplifier
1591928 variables, 4815428 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591929 variables, 4815435 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 512
Solving with MiniSAT 2.2.0 without simplifier
1591930 variables, 4815435 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 256
Solving with MiniSAT 2.2.0 without simplifier
1591931 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 128
Solving with MiniSAT 2.2.0 without simplifier
1591932 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 64
Solving with MiniSAT 2.2.0 without simplifier
1591933 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 32
Solving with MiniSAT 2.2.0 without simplifier
1591934 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 16
Solving with MiniSAT 2.2.0 without simplifier
1591935 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 8
Solving with MiniSAT 2.2.0 without simplifier
1591936 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 4
Solving with MiniSAT 2.2.0 without simplifier
1591937 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
weight 2
Solving with MiniSAT 2.2.0 without simplifier
1591938 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591939 variables, 4815320 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
weight 1
Solving with MiniSAT 2.2.0 without simplifier
1591940 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Solving with MiniSAT 2.2.0 without simplifier
1591941 variables, 4815320 clauses
SAT checker: negated claim is UNSATISFIABLE, i.e., holds
Solving with MiniSAT 2.2.0 without simplifier
1591941 variables, 4815320 clauses
SAT checker: negated claim is SATISFIABLE, i.e., does not hold
Building error trace

Counterexample:

State 25 file COV_harness.c line 14 function main thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)

State 26 file COV_harness.c line 14 function main thread 0
----------------------------------------------------
  v=0 (00000000000000000000000000000000)

State 27 file COV_harness.c line 14 function main thread 0
----------------------------------------------------
  prev=0 (00000000000000000000000000000000)

State 28 file COV_harness.c line 15 function main thread 0
----------------------------------------------------
  s=0 (00000000000000000000000000000000)

State 29 file COV_harness.c line 15 function main thread 0
----------------------------------------------------
  s=3 (00000000000000000000000000000011)

State 31 file COV_harness.c line 17 function main thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)

State 33 file COV_harness.c line 18 function main thread 0
----------------------------------------------------
  v=-2147483648 (10000000000000000000000000000000)
LOG: ref[0] = -2147483648


State 35 file COV_harness.c line 20 function main thread 0
----------------------------------------------------
  ref[0]=-2147483648 (10000000000000000000000000000000)

State 36 file COV_harness.c line 21 function main thread 0
----------------------------------------------------
  a[0]=-2147483648 (10000000000000000000000000000000)

State 37 file COV_harness.c line 17 function main thread 0
----------------------------------------------------
  i=1 (00000000000000000000000000000001)

State 40 file COV_harness.c line 18 function main thread 0
----------------------------------------------------
  v=0 (00000000000000000000000000000000)
LOG: ref[1] = 0


State 42 file COV_harness.c line 20 function main thread 0
----------------------------------------------------
  ref[1]=0 (00000000000000000000000000000000)

State 43 file COV_harness.c line 21 function main thread 0
----------------------------------------------------
  a[1]=0 (00000000000000000000000000000000)

State 44 file COV_harness.c line 17 function main thread 0
----------------------------------------------------
  i=2 (00000000000000000000000000000010)

State 47 file COV_harness.c line 18 function main thread 0
----------------------------------------------------
  v=-2147483648 (10000000000000000000000000000000)
LOG: ref[2] = -2147483648


State 49 file COV_harness.c line 20 function main thread 0
----------------------------------------------------
  ref[2]=-2147483648 (10000000000000000000000000000000)

State 50 file COV_harness.c line 21 function main thread 0
----------------------------------------------------
  a[2]=-2147483648 (10000000000000000000000000000000)

State 51 file COV_harness.c line 17 function main thread 0
----------------------------------------------------
  i=3 (00000000000000000000000000000011)

State 56 file COV_harness.c line 23 function main thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 57 file COV_harness.c line 23 function main thread 0
----------------------------------------------------
  size=3 (00000000000000000000000000000011)

State 60 file BRANCHCOV_mutant100065_qsort2.c line 62 function sort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 61 file BRANCHCOV_mutant100065_qsort2.c line 62 function sort thread 0
----------------------------------------------------
  l=0 (00000000000000000000000000000000)

State 62 file BRANCHCOV_mutant100065_qsort2.c line 62 function sort thread 0
----------------------------------------------------
  r=2 (00000000000000000000000000000010)
LOG: quicksort called with l=0, r=2


State 64 file BRANCHCOV_mutant100065_qsort2.c line 15 function quickSort thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 66 file BRANCHCOV_mutant100065_qsort2.c line 18 function quickSort thread 0
----------------------------------------------------
  __covered0=1 (00000000000000000000000000000001)

State 67 file BRANCHCOV_mutant100065_qsort2.c line 18 function quickSort thread 0
----------------------------------------------------
  total_covered=1 (00000000000000000000000000000001)

State 70 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 71 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  l=0 (00000000000000000000000000000000)

State 72 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  r=2 (00000000000000000000000000000010)

State 73 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  pivot=0 (00000000000000000000000000000000)

State 74 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)

State 75 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 76 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  t=0 (00000000000000000000000000000000)

State 80 file BRANCHCOV_mutant100065_qsort2.c line 31 function partition thread 0
----------------------------------------------------
  pivot=-2147483648 (10000000000000000000000000000000)

State 81 file BRANCHCOV_mutant100065_qsort2.c line 32 function partition thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)

State 82 file BRANCHCOV_mutant100065_qsort2.c line 33 function partition thread 0
----------------------------------------------------
  j=3 (00000000000000000000000000000011)

State 83 file BRANCHCOV_mutant100065_qsort2.c line 38 function partition thread 0
----------------------------------------------------
  __covered1=1 (00000000000000000000000000000001)

State 84 file BRANCHCOV_mutant100065_qsort2.c line 38 function partition thread 0
----------------------------------------------------
  total_covered=2 (00000000000000000000000000000010)

State 85 file BRANCHCOV_mutant100065_qsort2.c line 39 function partition thread 0
----------------------------------------------------
  i=1 (00000000000000000000000000000001)

State 95 file BRANCHCOV_mutant100065_qsort2.c line 42 function partition thread 0
----------------------------------------------------
  __covered2=1 (00000000000000000000000000000001)

State 96 file BRANCHCOV_mutant100065_qsort2.c line 42 function partition thread 0
----------------------------------------------------
  total_covered=3 (00000000000000000000000000000011)

State 97 file BRANCHCOV_mutant100065_qsort2.c line 43 function partition thread 0
----------------------------------------------------
  j=2 (00000000000000000000000000000010)

State 110 file BRANCHCOV_mutant100065_qsort2.c line 49 function partition thread 0
----------------------------------------------------
  t=0 (00000000000000000000000000000000)

State 111 file BRANCHCOV_mutant100065_qsort2.c line 50 function partition thread 0
----------------------------------------------------
  mutant_covered=1 (00000000000000000000000000000001)

State 115 file BRANCHCOV_mutant100065_qsort2.c line 52 function partition thread 0
----------------------------------------------------
  a[2]=0 (00000000000000000000000000000000)

State 118 file BRANCHCOV_mutant100065_qsort2.c line 39 function partition thread 0
----------------------------------------------------
  i=2 (00000000000000000000000000000010)

State 130 file BRANCHCOV_mutant100065_qsort2.c line 43 function partition thread 0
----------------------------------------------------
  j=1 (00000000000000000000000000000001)

State 138 file BRANCHCOV_mutant100065_qsort2.c line 43 function partition thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 146 file BRANCHCOV_mutant100065_qsort2.c line 46 function partition thread 0
----------------------------------------------------
  __covered3=1 (00000000000000000000000000000001)

State 147 file BRANCHCOV_mutant100065_qsort2.c line 46 function partition thread 0
----------------------------------------------------
  total_covered=4 (00000000000000000000000000000100)

State 152 file BRANCHCOV_mutant100065_qsort2.c line 54 function partition thread 0
----------------------------------------------------
  t=-2147483648 (10000000000000000000000000000000)

State 156 file BRANCHCOV_mutant100065_qsort2.c line 55 function partition thread 0
----------------------------------------------------
  a[0]=-2147483648 (10000000000000000000000000000000)

State 162 file BRANCHCOV_mutant100065_qsort2.c line 56 function partition thread 0
----------------------------------------------------
  a[0]=-2147483648 (10000000000000000000000000000000)

State 166 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 169 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 170 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  l=0 (00000000000000000000000000000000)

State 171 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  r=-1 (11111111111111111111111111111111)
LOG: quicksort called with l=0, r=-1


State 173 file BRANCHCOV_mutant100065_qsort2.c line 15 function quickSort thread 0
----------------------------------------------------
  j=1073740796 (00111111111111111111101111111100)

State 178 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 179 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  l=1 (00000000000000000000000000000001)

State 180 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  r=2 (00000000000000000000000000000010)
LOG: quicksort called with l=1, r=2


State 182 file BRANCHCOV_mutant100065_qsort2.c line 15 function quickSort thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 187 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 188 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  l=1 (00000000000000000000000000000001)

State 189 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  r=2 (00000000000000000000000000000010)

State 190 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  pivot=0 (00000000000000000000000000000000)

State 191 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)

State 192 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 193 file BRANCHCOV_mutant100065_qsort2.c line 30 function partition thread 0
----------------------------------------------------
  t=0 (00000000000000000000000000000000)

State 199 file BRANCHCOV_mutant100065_qsort2.c line 31 function partition thread 0
----------------------------------------------------
  pivot=0 (00000000000000000000000000000000)

State 200 file BRANCHCOV_mutant100065_qsort2.c line 32 function partition thread 0
----------------------------------------------------
  i=1 (00000000000000000000000000000001)

State 201 file BRANCHCOV_mutant100065_qsort2.c line 33 function partition thread 0
----------------------------------------------------
  j=3 (00000000000000000000000000000011)

State 203 file BRANCHCOV_mutant100065_qsort2.c line 39 function partition thread 0
----------------------------------------------------
  i=2 (00000000000000000000000000000010)

State 215 file BRANCHCOV_mutant100065_qsort2.c line 39 function partition thread 0
----------------------------------------------------
  i=3 (00000000000000000000000000000011)

State 221 file BRANCHCOV_mutant100065_qsort2.c line 43 function partition thread 0
----------------------------------------------------
  j=2 (00000000000000000000000000000010)

State 236 file BRANCHCOV_mutant100065_qsort2.c line 54 function partition thread 0
----------------------------------------------------
  t=0 (00000000000000000000000000000000)

State 240 file BRANCHCOV_mutant100065_qsort2.c line 55 function partition thread 0
----------------------------------------------------
  a[1]=0 (00000000000000000000000000000000)

State 246 file BRANCHCOV_mutant100065_qsort2.c line 56 function partition thread 0
----------------------------------------------------
  a[2]=0 (00000000000000000000000000000000)

State 250 file BRANCHCOV_mutant100065_qsort2.c line 20 function quickSort thread 0
----------------------------------------------------
  j=2 (00000000000000000000000000000010)

State 253 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 254 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  l=1 (00000000000000000000000000000001)

State 255 file BRANCHCOV_mutant100065_qsort2.c line 21 function quickSort thread 0
----------------------------------------------------
  r=1 (00000000000000000000000000000001)
LOG: quicksort called with l=1, r=1


State 257 file BRANCHCOV_mutant100065_qsort2.c line 15 function quickSort thread 0
----------------------------------------------------
  j=-401 (11111111111111111111111001101111)

State 262 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  a=a (0000001000000000000000000000000000000000000000000000000000000000)

State 263 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  l=3 (00000000000000000000000000000011)

State 264 file BRANCHCOV_mutant100065_qsort2.c line 22 function quickSort thread 0
----------------------------------------------------
  r=2 (00000000000000000000000000000010)
LOG: quicksort called with l=3, r=2


State 266 file BRANCHCOV_mutant100065_qsort2.c line 15 function quickSort thread 0
----------------------------------------------------
  j=0 (00000000000000000000000000000000)

State 272 file COV_harness.c line 24 function main thread 0
----------------------------------------------------
  prev=-2147483648 (10000000000000000000000000000000)
LOG: checking -2147483648


State 274 file COV_harness.c line 26 function main thread 0
----------------------------------------------------
  i=0 (00000000000000000000000000000000)
LOG: a[0] = -2147483648


State 278 file COV_harness.c line 29 function main thread 0
----------------------------------------------------
  prev=-2147483648 (10000000000000000000000000000000)

State 279 file COV_harness.c line 26 function main thread 0
----------------------------------------------------
  i=1 (00000000000000000000000000000001)
LOG: a[1] = 0


State 284 file COV_harness.c line 29 function main thread 0
----------------------------------------------------
  prev=0 (00000000000000000000000000000000)

State 285 file COV_harness.c line 26 function main thread 0
----------------------------------------------------
  i=2 (00000000000000000000000000000010)
LOG: a[2] = 0


State 290 file COV_harness.c line 29 function main thread 0
----------------------------------------------------
  prev=0 (00000000000000000000000000000000)

State 291 file COV_harness.c line 26 function main thread 0
----------------------------------------------------
  i=3 (00000000000000000000000000000011)

Violated property:
  file COV_harness.c line 33 function main
  assertion !(mutant_covered != 0)
  !(mutant_covered != 0)

VERIFICATION FAILED
